import React from 'react';
import CivicEmblem from './CivicEmblem';

export default function Footer({ onNavigate }) {
  return (
    <footer className="w-full bg-[#002548] text-[#edf0ff] border-t border-[#c3c6d0]/20 pt-12 pb-8">
      {/* Subtle National Accent Border */}
      <div className="w-full h-1 bg-gradient-to-r from-[#F59E0B] via-[#FFFFFF] to-[#168A55] opacity-80 -mt-12 mb-12" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-12 gap-8 pb-10 border-b border-[#c3c6d0]/20">
          {/* Brand & Mandate */}
          <div className="md:col-span-5 flex flex-col gap-3">
            <div className="bg-white/10 p-2.5 rounded-lg inline-flex w-fit backdrop-blur-xs">
              <CivicEmblem showText={false} />
              <div className="ml-2.5 flex flex-col justify-center">
                <span className="font-headline-md text-headline-md font-bold text-white tracking-wide">
                  EVENT HORIZON
                </span>
                <span className="font-label-sm text-label-sm text-[#ffddb8] uppercase font-bold">
                  Sovereign RTI Intelligence Portal
                </span>
              </div>
            </div>

            <p className="font-body-md text-body-md text-[#edf0ff]/80 max-w-sm mt-1 leading-relaxed">
              AI-assisted statutory routing for the Right to Information Act, 2005. Designed to eliminate the "RTI Black Hole" through transparent, explainable, tri-state jurisdiction resolution.
            </p>

            <div className="inline-flex items-center gap-2 text-xs text-[#d3e3ff] mt-2 font-mono">
              <span className="px-2 py-0.5 rounded bg-white/10 border border-white/20">PS No. CX0107</span>
              <span>•</span>
              <span className="px-2 py-0.5 rounded bg-white/10 border border-white/20">MUSA CodeX 2026</span>
              <span>•</span>
              <span>Team Tensor Float</span>
            </div>
          </div>

          {/* Quick Navigation Links */}
          <div className="md:col-span-3 flex flex-col gap-2">
            <span className="font-label-sm text-label-sm uppercase font-bold text-[#ffddb8] tracking-wider mb-1">
              Statutory Platform
            </span>
            <button
              type="button"
              onClick={() => onNavigate('home-analyzer')}
              className="text-left font-body-sm text-body-sm text-[#edf0ff]/80 hover:text-white transition-colors"
            >
              RTI Application Analyzer
            </button>
            <button
              type="button"
              onClick={() => onNavigate('star-map')}
              className="text-left font-body-sm text-body-sm text-[#edf0ff]/80 hover:text-white transition-colors"
            >
              Star Map Knowledge Base
            </button>
            <button
              type="button"
              onClick={() => onNavigate('escape-velocity-engine')}
              className="text-left font-body-sm text-body-sm text-[#edf0ff]/80 hover:text-white transition-colors"
            >
              Escape Velocity Decision Engine
            </button>
            <button
              type="button"
              onClick={() => onNavigate('how-it-works')}
              className="text-left font-body-sm text-body-sm text-[#edf0ff]/80 hover:text-white transition-colors"
            >
              How It Works &amp; Pipeline
            </button>
          </div>

          {/* Legal and Compliance */}
          <div className="md:col-span-4 flex flex-col gap-2">
            <span className="font-label-sm text-label-sm uppercase font-bold text-[#ffddb8] tracking-wider mb-1">
              Ethical &amp; Legal Disclaimers
            </span>
            <p className="font-body-sm text-body-sm text-[#edf0ff]/70 leading-relaxed">
              <strong>Section 4(1)(b) Compliance:</strong> Recommendations generated by this engine are algorithmic aids under pilot evaluation. They do not supersede gazetted rules of business or statutory PIO jurisdiction determinations.
            </p>
            <div className="mt-2 p-2 rounded bg-white/5 border border-white/10 font-body-sm text-[11px] text-[#edf0ff]/60">
              Zero Data Retention: Input text and draft queries in demo mode are processed ephemerally without persistent logging.
            </div>
          </div>
        </div>

        {/* Sub-Footer */}
        <div className="pt-6 flex flex-col sm:flex-row items-center justify-between gap-4 font-body-sm text-body-sm text-[#edf0ff]/60">
          <div>
            © 2026 Event Horizon • Government of India Civic Tech Initiative (Pilot) • All Rights Reserved
          </div>
          <div className="flex items-center gap-4 text-xs">
            <span className="hover:underline cursor-pointer">Section 6(1) Standards</span>
            <span>•</span>
            <span className="hover:underline cursor-pointer">Section 6(3) Transfers</span>
            <span>•</span>
            <span className="hover:underline cursor-pointer">NIC Schema Compliant</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
